- Fruits
-- What is a dragonfruit? : "Fruits/dragonfruit.jpg" It is a fruit with a lot of seeds.
-- Fruits that are star
--- What is a starfruit? : Starfruit



- 
{ 
	"Name" : "Fruits", 
	"Answer" : None 
}
-- 
	{ 
		"Name" : "What is a dragonfruit?", 
		"Answer" : "It is a fruit with a lot of seeds.", 
		"Media" : "Fruits/dragonfruit.jpg"
	}
-- 
	{ 
		"Name" : "Fruits that are star", 
		"Answer" : None 
	}
--- 
		{ 
			"Name" : "What is a starfruit?", 
			"Answer" : "Starfruit" 
		}